// Generated by dts-bundle-generator v9.5.1

export declare const publicAppRouter: import("@trpc/server").TRPCBuiltRouter<{
	ctx: {
		request: unknown;
		user: {
			sub: string;
		};
		accessibleAccountIds: string[];
		authType: string;
		apiKeyId: string;
	} | {
		user: null;
		accessibleAccountIds: string[];
		authType: string;
		request: unknown;
	} | {
		user: {
			sub: string;
			email?: string;
		};
		accessibleAccountIds: string[];
		authType: string;
		request: unknown;
	};
	meta: object;
	errorShape: import("@trpc/server").TRPCDefaultErrorShape;
	transformer: false;
}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
	readonly "accounts/list": import("@trpc/server").TRPCQueryProcedure<{
		input: void;
		output: {
			items: {
				accountId: string;
				countryCode: string | null;
				name: string | null;
			}[];
		};
		meta: object;
	}>;
	readonly "campaigns/list": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
		};
		output: {
			items: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			}[];
		};
		meta: object;
	}>;
	readonly "campaigns/get": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/create": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			name: string;
			budget: number;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/update": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
			name?: string | undefined;
			startDateTime?: string | undefined;
			endDateTime?: string | null | undefined;
			portfolioId?: string | null | undefined;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/pause": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/resume": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/delete": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/set-budget": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
			budget: number;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/set-bid-strategy": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
			strategy: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE";
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/set-bid-adjustments": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
			scope: "placement" | "audience" | "creative";
			adjustments?: any;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/list": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
		};
		output: {
			items: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			}[];
		};
		meta: object;
	}>;
	readonly "ad-groups/get": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/create": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
			name: string;
			defaultBid: number;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/update": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
			name: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/set-default-bid": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			value: number;
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/pause": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/resume": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/delete": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ads/list": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			productAsin?: string | undefined;
		};
		output: {
			items: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				adId: string;
				productIdType: "ASIN" | "SKU";
				productId: string;
				productTitle: string | null;
			}[];
		};
		meta: object;
	}>;
	readonly "ads/get": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				adId: string;
				productIdType: "ASIN" | "SKU";
				productId: string;
				productTitle: string | null;
			};
		};
		meta: object;
	}>;
	readonly "ads/create": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
			productIdType: "ASIN" | "SKU";
			productId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				adId: string;
				productIdType: "ASIN" | "SKU";
				productId: string;
				productTitle: string | null;
			};
		};
		meta: object;
	}>;
	readonly "ads/update": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
			adId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				adId: string;
				productIdType: "ASIN" | "SKU";
				productId: string;
				productTitle: string | null;
			};
		};
		meta: object;
	}>;
	readonly "ads/delete": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adId: string;
		};
		output: {
			adId: string;
			deleted: true;
		};
		meta: object;
	}>;
	readonly "asins/get": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			asin: string;
		};
		output: {
			campaigns: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				creationDateTime: string | null;
				targets: {
					type: "KEYWORD" | "PRODUCT" | "AUTO";
					state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
					campaignId: string;
					adGroupId: string | null;
					negative: boolean;
					targetId: string;
					bid: number | null;
					productIdType?: "ASIN" | "SKU" | null | undefined;
					productId?: string | null | undefined;
					targetMatchType?: string | null | undefined;
					keyword?: string | null | undefined;
					keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
					productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
				}[];
				campaignName: string;
				adGroups: {
					state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
					campaignId: string;
					adGroupId: string;
					name: string;
					defaultBid: number;
					targets: {
						type: "KEYWORD" | "PRODUCT" | "AUTO";
						state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
						campaignId: string;
						adGroupId: string | null;
						negative: boolean;
						targetId: string;
						bid: number | null;
						productIdType?: "ASIN" | "SKU" | null | undefined;
						productId?: string | null | undefined;
						targetMatchType?: string | null | undefined;
						keyword?: string | null | undefined;
						keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
						productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
					}[];
					ads: {
						state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
						campaignId: string;
						adGroupId: string;
						adId: string;
						productIdType: "ASIN" | "SKU";
						productId: string;
						productTitle: string | null;
					}[];
				}[];
			}[];
		};
		meta: object;
	}>;
	readonly "history/list": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			entityType: "campaign" | "adGroup" | "ad" | "target";
			entityId: string;
			range?: string | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
		};
		output: {
			items: {
				entityType: "campaign" | "adGroup" | "ad" | "target";
				entityId: string;
				id: string;
				eventType: "bid_change" | "state_change" | "budget_change";
				fieldName: string;
				previousValue: string | null;
				newValue: string | null;
				changedAt: string;
				source: "bidbeacon" | "ams" | "change_history";
			}[];
		};
		meta: object;
	}>;
	readonly "targets/list": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			negative?: boolean | undefined;
		};
		output: {
			items: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			}[];
		};
		meta: object;
	}>;
	readonly "targets/get": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			targetId: string;
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "targets/create/keyword": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
			bid: number;
			keyword: string;
			matchType: "BROAD" | "PHRASE" | "EXACT";
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "targets/create/product": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
			productIdType: "ASIN" | "SKU";
			productId: string;
			bid: number;
			matchType: "PRODUCT_EXACT" | "PRODUCT_SIMILAR";
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "targets/delete": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			targetId: string;
		};
		output: {
			targetId: string;
			deleted: true;
		};
		meta: object;
	}>;
	readonly "targets/pause": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			targetId: string;
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "targets/resume": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			targetId: string;
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "bids/set": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			value: number;
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			targetId: string;
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "bids/adjust": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			targetId: string;
			delta: number;
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "metrics/series/campaigns": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
			bucket?: "auto" | "hour" | "day" | "week" | "month" | "year" | undefined;
		};
		output: {
			range: {
				startDate: string;
				endDate: string;
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			series: {
				start: string;
				end: string;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			}[];
			granularity: "hour" | "day" | "week" | "month" | "year";
			timezone: string;
		};
		meta: object;
	}>;
	readonly "metrics/series/ad-groups": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
			bucket?: "auto" | "hour" | "day" | "week" | "month" | "year" | undefined;
		};
		output: {
			range: {
				startDate: string;
				endDate: string;
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			series: {
				start: string;
				end: string;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			}[];
			granularity: "hour" | "day" | "week" | "month" | "year";
			timezone: string;
		};
		meta: object;
	}>;
	readonly "metrics/series/ads": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
			bucket?: "auto" | "hour" | "day" | "week" | "month" | "year" | undefined;
		};
		output: {
			range: {
				startDate: string;
				endDate: string;
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			series: {
				start: string;
				end: string;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			}[];
			granularity: "hour" | "day" | "week" | "month" | "year";
			timezone: string;
		};
		meta: object;
	}>;
	readonly "metrics/series/targets": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
			bucket?: "auto" | "hour" | "day" | "week" | "month" | "year" | undefined;
		};
		output: {
			range: {
				startDate: string;
				endDate: string;
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			series: {
				start: string;
				end: string;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			}[];
			granularity: "hour" | "day" | "week" | "month" | "year";
			timezone: string;
		};
		meta: object;
	}>;
	readonly "metrics/table/campaigns": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			sort?: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			} | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
		};
		output: {
			sort: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			items: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | null;
				campaignId: string;
				name: string | null;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			}[];
		};
		meta: object;
	}>;
	readonly "metrics/table/ad-groups": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			sort?: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			} | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
		};
		output: {
			sort: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			items: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | null;
				campaignId: string;
				adGroupId: string;
				name: string | null;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
				campaignName: string | null;
			}[];
		};
		meta: object;
	}>;
	readonly "metrics/table/ads": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			sort?: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			} | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
		};
		output: {
			sort: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			items: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | null;
				campaignId: string;
				adGroupId: string;
				adId: string;
				productId: string | null;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
				campaignName: string | null;
				adGroupName: string | null;
			}[];
		};
		meta: object;
	}>;
	readonly "metrics/table/targets": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			sort?: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			} | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
		};
		output: {
			sort: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			items: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | null;
				campaignId: string;
				adGroupId: string | null;
				productId: string | null;
				targetId: string;
				targetMatchType: string | null;
				keyword: string | null;
				keywordMatchType: "BROAD" | "PHRASE" | "EXACT" | null;
				productMatchType: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
				campaignName: string | null;
				adGroupName: string | null;
			}[];
		};
		meta: object;
	}>;
	readonly "enums/bid-strategy": import("@trpc/server").TRPCQueryProcedure<{
		input: void;
		output: {
			items: ("MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE")[];
		};
		meta: object;
	}>;
	readonly "enums/match-type": import("@trpc/server").TRPCQueryProcedure<{
		input: void;
		output: {
			keyword: ("BROAD" | "PHRASE" | "EXACT")[];
			product: ("PRODUCT_EXACT" | "PRODUCT_SIMILAR")[];
		};
		meta: object;
	}>;
	readonly "enums/placement": import("@trpc/server").TRPCQueryProcedure<{
		input: void;
		output: {
			items: ("HOME_PAGE" | "TOP_OF_SEARCH" | "REST_OF_SEARCH" | "PRODUCT_PAGE" | "SITE_AMAZON_BUSINESS")[];
		};
		meta: object;
	}>;
	readonly "enums/state": import("@trpc/server").TRPCQueryProcedure<{
		input: void;
		output: {
			items: ("ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER")[];
		};
		meta: object;
	}>;
}>>;
export declare const cliAppRouter: import("@trpc/server").TRPCBuiltRouter<{
	ctx: {
		request: unknown;
		user: {
			sub: string;
		};
		accessibleAccountIds: string[];
		authType: string;
		apiKeyId: string;
	} | {
		user: null;
		accessibleAccountIds: string[];
		authType: string;
		request: unknown;
	} | {
		user: {
			sub: string;
			email?: string;
		};
		accessibleAccountIds: string[];
		authType: string;
		request: unknown;
	};
	meta: object;
	errorShape: import("@trpc/server").TRPCDefaultErrorShape;
	transformer: false;
}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
	readonly "accounts/list": import("@trpc/server").TRPCQueryProcedure<{
		input: void;
		output: {
			items: {
				accountId: string;
				countryCode: string | null;
				name: string | null;
			}[];
		};
		meta: object;
	}>;
	readonly "campaigns/list": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
		};
		output: {
			items: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			}[];
		};
		meta: object;
	}>;
	readonly "campaigns/get": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/create": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			name: string;
			budget: number;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/update": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
			name?: string | undefined;
			startDateTime?: string | undefined;
			endDateTime?: string | null | undefined;
			portfolioId?: string | null | undefined;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/pause": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/resume": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/delete": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/set-budget": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
			budget: number;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/set-bid-strategy": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
			strategy: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE";
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "campaigns/set-bid-adjustments": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
			scope: "placement" | "audience" | "creative";
			adjustments?: any;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				name: string;
				budget: number;
				creationDateTime: string | null;
				lastUpdatedDateTime: string | null;
				bidStrategy?: "MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE" | null | undefined;
				startDateTime?: string | null | undefined;
				endDateTime?: string | null | undefined;
				portfolioId?: string | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/list": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
		};
		output: {
			items: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			}[];
		};
		meta: object;
	}>;
	readonly "ad-groups/get": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/create": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			campaignId: string;
			name: string;
			defaultBid: number;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/update": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
			name: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/set-default-bid": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			value: number;
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/pause": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/resume": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ad-groups/delete": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				name: string;
				defaultBid: number;
			};
		};
		meta: object;
	}>;
	readonly "ads/list": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			productAsin?: string | undefined;
		};
		output: {
			items: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				adId: string;
				productIdType: "ASIN" | "SKU";
				productId: string;
				productTitle: string | null;
			}[];
		};
		meta: object;
	}>;
	readonly "ads/get": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				adId: string;
				productIdType: "ASIN" | "SKU";
				productId: string;
				productTitle: string | null;
			};
		};
		meta: object;
	}>;
	readonly "ads/create": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
			productIdType: "ASIN" | "SKU";
			productId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				adId: string;
				productIdType: "ASIN" | "SKU";
				productId: string;
				productTitle: string | null;
			};
		};
		meta: object;
	}>;
	readonly "ads/update": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
			adId: string;
		};
		output: {
			item: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string;
				adId: string;
				productIdType: "ASIN" | "SKU";
				productId: string;
				productTitle: string | null;
			};
		};
		meta: object;
	}>;
	readonly "ads/delete": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adId: string;
		};
		output: {
			adId: string;
			deleted: true;
		};
		meta: object;
	}>;
	readonly "asins/get": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			asin: string;
		};
		output: {
			campaigns: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				creationDateTime: string | null;
				targets: {
					type: "KEYWORD" | "PRODUCT" | "AUTO";
					state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
					campaignId: string;
					adGroupId: string | null;
					negative: boolean;
					targetId: string;
					bid: number | null;
					productIdType?: "ASIN" | "SKU" | null | undefined;
					productId?: string | null | undefined;
					targetMatchType?: string | null | undefined;
					keyword?: string | null | undefined;
					keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
					productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
				}[];
				campaignName: string;
				adGroups: {
					state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
					campaignId: string;
					adGroupId: string;
					name: string;
					defaultBid: number;
					targets: {
						type: "KEYWORD" | "PRODUCT" | "AUTO";
						state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
						campaignId: string;
						adGroupId: string | null;
						negative: boolean;
						targetId: string;
						bid: number | null;
						productIdType?: "ASIN" | "SKU" | null | undefined;
						productId?: string | null | undefined;
						targetMatchType?: string | null | undefined;
						keyword?: string | null | undefined;
						keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
						productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
					}[];
					ads: {
						state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
						campaignId: string;
						adGroupId: string;
						adId: string;
						productIdType: "ASIN" | "SKU";
						productId: string;
						productTitle: string | null;
					}[];
				}[];
			}[];
		};
		meta: object;
	}>;
	readonly "history/list": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			entityType: "campaign" | "adGroup" | "ad" | "target";
			entityId: string;
			range?: string | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
		};
		output: {
			items: {
				entityType: "campaign" | "adGroup" | "ad" | "target";
				entityId: string;
				id: string;
				eventType: "bid_change" | "state_change" | "budget_change";
				fieldName: string;
				previousValue: string | null;
				newValue: string | null;
				changedAt: string;
				source: "bidbeacon" | "ams" | "change_history";
			}[];
		};
		meta: object;
	}>;
	readonly "targets/list": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			negative?: boolean | undefined;
		};
		output: {
			items: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			}[];
		};
		meta: object;
	}>;
	readonly "targets/get": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			targetId: string;
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "targets/create/keyword": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
			bid: number;
			keyword: string;
			matchType: "BROAD" | "PHRASE" | "EXACT";
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "targets/create/product": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			adGroupId: string;
			productIdType: "ASIN" | "SKU";
			productId: string;
			bid: number;
			matchType: "PRODUCT_EXACT" | "PRODUCT_SIMILAR";
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "targets/delete": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			targetId: string;
		};
		output: {
			targetId: string;
			deleted: true;
		};
		meta: object;
	}>;
	readonly "targets/pause": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			targetId: string;
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "targets/resume": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			targetId: string;
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "bids/set": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			value: number;
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			targetId: string;
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "bids/adjust": import("@trpc/server").TRPCMutationProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			targetId: string;
			delta: number;
		};
		output: {
			item: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER";
				campaignId: string;
				adGroupId: string | null;
				negative: boolean;
				targetId: string;
				bid: number | null;
				productIdType?: "ASIN" | "SKU" | null | undefined;
				productId?: string | null | undefined;
				targetMatchType?: string | null | undefined;
				keyword?: string | null | undefined;
				keywordMatchType?: "BROAD" | "PHRASE" | "EXACT" | null | undefined;
				productMatchType?: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null | undefined;
			};
		};
		meta: object;
	}>;
	readonly "metrics/series/campaigns": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
			bucket?: "auto" | "hour" | "day" | "week" | "month" | "year" | undefined;
		};
		output: {
			range: {
				startDate: string;
				endDate: string;
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			series: {
				start: string;
				end: string;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			}[];
			granularity: "hour" | "day" | "week" | "month" | "year";
			timezone: string;
		};
		meta: object;
	}>;
	readonly "metrics/series/ad-groups": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
			bucket?: "auto" | "hour" | "day" | "week" | "month" | "year" | undefined;
		};
		output: {
			range: {
				startDate: string;
				endDate: string;
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			series: {
				start: string;
				end: string;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			}[];
			granularity: "hour" | "day" | "week" | "month" | "year";
			timezone: string;
		};
		meta: object;
	}>;
	readonly "metrics/series/ads": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
			bucket?: "auto" | "hour" | "day" | "week" | "month" | "year" | undefined;
		};
		output: {
			range: {
				startDate: string;
				endDate: string;
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			series: {
				start: string;
				end: string;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			}[];
			granularity: "hour" | "day" | "week" | "month" | "year";
			timezone: string;
		};
		meta: object;
	}>;
	readonly "metrics/series/targets": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
			bucket?: "auto" | "hour" | "day" | "week" | "month" | "year" | undefined;
		};
		output: {
			range: {
				startDate: string;
				endDate: string;
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			series: {
				start: string;
				end: string;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			}[];
			granularity: "hour" | "day" | "week" | "month" | "year";
			timezone: string;
		};
		meta: object;
	}>;
	readonly "metrics/table/campaigns": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			sort?: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			} | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
		};
		output: {
			sort: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			items: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | null;
				campaignId: string;
				name: string | null;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			}[];
		};
		meta: object;
	}>;
	readonly "metrics/table/ad-groups": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			sort?: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			} | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
		};
		output: {
			sort: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			items: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | null;
				campaignId: string;
				adGroupId: string;
				name: string | null;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
				campaignName: string | null;
			}[];
		};
		meta: object;
	}>;
	readonly "metrics/table/ads": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			sort?: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			} | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
		};
		output: {
			sort: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			items: {
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | null;
				campaignId: string;
				adGroupId: string;
				adId: string;
				productId: string | null;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
				campaignName: string | null;
				adGroupName: string | null;
			}[];
		};
		meta: object;
	}>;
	readonly "metrics/table/targets": import("@trpc/server").TRPCQueryProcedure<{
		input: {
			config: {
				accountId: string;
				range: string;
				countryCode?: string | undefined;
			};
			range?: string | undefined;
			sort?: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			} | undefined;
			limit?: number | undefined;
			offset?: number | undefined;
			campaignId?: string | undefined;
			adGroupId?: string | undefined;
			metrics?: ("impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas")[] | undefined;
			ids?: string[] | undefined;
			filters?: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | "ALL" | undefined;
				budget?: {
					min?: number | undefined;
					max?: number | undefined;
				} | undefined;
				targetMatchType?: string | undefined;
				metrics?: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", {
					min?: number | undefined;
					max?: number | undefined;
				}>> | undefined;
				endDate?: {
					before?: string | undefined;
					after?: string | undefined;
				} | undefined;
				search?: string | undefined;
				targeting?: "MANUAL" | "AUTO" | undefined;
				targetType?: "KEYWORD" | "PRODUCT" | "AUTO" | undefined;
				outOfBudget?: boolean | undefined;
			} | undefined;
		};
		output: {
			sort: {
				field: "impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas";
				direction: "asc" | "desc";
			};
			totals: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
			items: {
				type: "KEYWORD" | "PRODUCT" | "AUTO";
				state: "ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER" | null;
				campaignId: string;
				adGroupId: string | null;
				productId: string | null;
				targetId: string;
				targetMatchType: string | null;
				keyword: string | null;
				keywordMatchType: "BROAD" | "PHRASE" | "EXACT" | null;
				productMatchType: "PRODUCT_EXACT" | "PRODUCT_SIMILAR" | null;
				metrics: Partial<Record<"impressions" | "clicks" | "spend" | "purchases" | "sales" | "acos" | "cpc" | "ctr" | "roas", number | null>>;
				campaignName: string | null;
				adGroupName: string | null;
			}[];
		};
		meta: object;
	}>;
	readonly "enums/bid-strategy": import("@trpc/server").TRPCQueryProcedure<{
		input: void;
		output: {
			items: ("MANUAL" | "RULE_BASED" | "SALES_DOWN_ONLY" | "SALES_UP_AND_DOWN" | "SALES" | "NEW_TO_BRAND" | "NONE")[];
		};
		meta: object;
	}>;
	readonly "enums/match-type": import("@trpc/server").TRPCQueryProcedure<{
		input: void;
		output: {
			keyword: ("BROAD" | "PHRASE" | "EXACT")[];
			product: ("PRODUCT_EXACT" | "PRODUCT_SIMILAR")[];
		};
		meta: object;
	}>;
	readonly "enums/placement": import("@trpc/server").TRPCQueryProcedure<{
		input: void;
		output: {
			items: ("HOME_PAGE" | "TOP_OF_SEARCH" | "REST_OF_SEARCH" | "PRODUCT_PAGE" | "SITE_AMAZON_BUSINESS")[];
		};
		meta: object;
	}>;
	readonly "enums/state": import("@trpc/server").TRPCQueryProcedure<{
		input: void;
		output: {
			items: ("ENABLED" | "PAUSED" | "ARCHIVED" | "OTHER")[];
		};
		meta: object;
	}>;
}>>;
export type PublicAppRouter = typeof publicAppRouter;
export type CliAppRouter = PublicAppRouter;

export {};
