// Generated by dts-bundle-generator v9.5.1

export type AuthenticatedUser = {
	merchbaseUserId: string;
};
export type AuthType = "access" | "none";
export type CredentialKind = "api_key" | "oauth" | "session";
export type Context = {
	accessError: "access_denied" | "access_unavailable" | null;
	accessibleAccountIds: string[];
	accessibleAdvertiserAccountIds: string[];
	authType: AuthType;
	credentialKind: CredentialKind | null;
	operationContext?: unknown;
	request: unknown;
	user: AuthenticatedUser | null;
};
export type OperationErrorCode = "ACCOUNT_ACCESS_DENIED" | "AMAZON_REJECTED" | "AMAZON_UNAVAILABLE" | "AUTHENTICATION_REQUIRED" | "COMPOSITE_PARTIAL_FAILURE" | "CURSOR_INVALID" | "INTERNAL_ERROR" | "INVALID_INPUT" | "RESOURCE_NOT_FOUND";
export declare const publicAppRouter: import("@trpc/server").TRPCBuiltRouter<{
	ctx: Context;
	meta: object;
	errorShape: {
		data: {
			operationCode: OperationErrorCode;
			details: Record<string, unknown>;
			code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
			httpStatus: number;
			path?: string;
			stack?: string;
		} | {
			operationCode: string;
			details: {
				issues: import("zod").ZodIssue[];
			};
			code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
			httpStatus: number;
			path?: string;
			stack?: string;
		} | {
			code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
			httpStatus: number;
			path?: string;
			stack?: string;
		};
		message: string;
		code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
	};
	transformer: false;
}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
	readonly list_advertiser_accounts: import("@trpc/server").TRPCQueryProcedure<{
		input: {};
		output: {
			accounts: {
				id: string;
				name: string;
				countryCode: string;
				marketplaceId: string;
				currency: string;
				profileId: string | null;
				amazonAdsAccountId: string;
				timezone: string;
			}[];
		};
		meta: object;
	}>;
	readonly search: import("@trpc/server").TRPCQueryProcedure<{
		input: {
			accountId: string;
			resource: "campaign" | "ad_group" | "ad" | "target" | "product" | "change_event";
			orderBy?: {
				field: "campaign.id" | "campaign.name" | "campaign.state" | "campaign.deliveryStatus" | "campaign.dailyBudget" | "campaign.targetingMode" | "campaign.bidStrategy" | "campaign.startDate" | "campaign.endDate" | "adGroup.id" | "adGroup.name" | "adGroup.state" | "adGroup.deliveryStatus" | "adGroup.defaultBid" | "ad.id" | "ad.state" | "ad.deliveryStatus" | "ad.asin" | "ad.productTitle" | "ad.type" | "target.id" | "target.state" | "target.deliveryStatus" | "target.type" | "target.scope" | "target.bid" | "target.negative" | "target.keyword" | "target.asin" | "target.matchType" | "product.asin" | "product.title" | "changeEvent.id" | "changeEvent.resourceType" | "changeEvent.resourceId" | "changeEvent.eventType" | "changeEvent.field" | "changeEvent.previousValue" | "changeEvent.newValue" | "changeEvent.changedAt" | "changeEvent.source" | "metrics.impressions" | "metrics.clicks" | "metrics.spend" | "metrics.orders" | "metrics.sales" | "metrics.acos" | "metrics.cpc" | "metrics.ctr" | "metrics.roas" | "metrics.cvr" | "segments.date" | "segments.hour";
				direction: "asc" | "desc";
			}[] | undefined;
			limit?: number | undefined;
			fields?: ("campaign.id" | "campaign.name" | "campaign.state" | "campaign.deliveryStatus" | "campaign.dailyBudget" | "campaign.targetingMode" | "campaign.bidStrategy" | "campaign.startDate" | "campaign.endDate" | "adGroup.id" | "adGroup.name" | "adGroup.state" | "adGroup.deliveryStatus" | "adGroup.defaultBid" | "ad.id" | "ad.state" | "ad.deliveryStatus" | "ad.asin" | "ad.productTitle" | "ad.type" | "target.id" | "target.state" | "target.deliveryStatus" | "target.type" | "target.scope" | "target.bid" | "target.negative" | "target.keyword" | "target.asin" | "target.matchType" | "product.asin" | "product.title" | "changeEvent.id" | "changeEvent.resourceType" | "changeEvent.resourceId" | "changeEvent.eventType" | "changeEvent.field" | "changeEvent.previousValue" | "changeEvent.newValue" | "changeEvent.changedAt" | "changeEvent.source" | "metrics.impressions" | "metrics.clicks" | "metrics.spend" | "metrics.orders" | "metrics.sales" | "metrics.acos" | "metrics.cpc" | "metrics.ctr" | "metrics.roas" | "metrics.cvr" | "segments.date" | "segments.hour")[] | undefined;
			filters?: {
				field: "campaign.id" | "campaign.name" | "campaign.state" | "campaign.deliveryStatus" | "campaign.dailyBudget" | "campaign.targetingMode" | "campaign.bidStrategy" | "campaign.startDate" | "campaign.endDate" | "adGroup.id" | "adGroup.name" | "adGroup.state" | "adGroup.deliveryStatus" | "adGroup.defaultBid" | "ad.id" | "ad.state" | "ad.deliveryStatus" | "ad.asin" | "ad.productTitle" | "ad.type" | "target.id" | "target.state" | "target.deliveryStatus" | "target.type" | "target.scope" | "target.bid" | "target.negative" | "target.keyword" | "target.asin" | "target.matchType" | "product.asin" | "product.title" | "changeEvent.id" | "changeEvent.resourceType" | "changeEvent.resourceId" | "changeEvent.eventType" | "changeEvent.field" | "changeEvent.previousValue" | "changeEvent.newValue" | "changeEvent.changedAt" | "changeEvent.source" | "metrics.impressions" | "metrics.clicks" | "metrics.spend" | "metrics.orders" | "metrics.sales" | "metrics.acos" | "metrics.cpc" | "metrics.ctr" | "metrics.roas" | "metrics.cvr" | "segments.date" | "segments.hour";
				operator: "eq" | "in" | "contains" | "gt" | "gte" | "lt" | "lte";
				value?: unknown;
			}[] | undefined;
			dateRange?: {
				startDate: string;
				endDate: string;
			} | undefined;
			cursor?: string | undefined;
		};
		output: {
			context: {
				orderBy: {
					field: string;
					direction: "asc" | "desc";
				}[];
				fields: string[];
				account: {
					id: string;
					currency: string;
					timezone: string;
				};
				resource: "campaign" | "ad_group" | "ad" | "target" | "product" | "change_event";
				dateRange?: {
					startDate: string;
					endDate: string;
					source: "DEFAULT" | "EXPLICIT";
				} | undefined;
				coverage?: {
					status: "UNKNOWN" | "COMPLETE" | "INCOMPLETE";
					issues: ({
						date: string;
						status: "PENDING" | "FAILED" | "UNKNOWN";
					} | {
						date: string;
						status: "PARSE_ERRORS";
						errorCount: number;
					})[];
				} | undefined;
			};
			rows: Record<string, unknown>[];
			nextCursor?: string | undefined;
		};
		meta: object;
	}>;
	readonly create_sponsored_products_campaign: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			campaign: {
				name: string;
				state: "ENABLED" | "PAUSED";
				bidStrategy: "FIXED" | "DYNAMIC_DOWN_ONLY" | "DYNAMIC_UP_AND_DOWN";
				dailyBudget: number;
				startDate?: string | undefined;
				endDate?: string | null | undefined;
				placementBidAdjustments?: {
					topOfSearch?: number | undefined;
					restOfSearch?: number | undefined;
					productPages?: number | undefined;
					amazonBusiness?: number | undefined;
				} | undefined;
			};
			accountId: string;
			adGroup: {
				name: string;
				defaultBid: number;
			};
			asins: string[];
			targeting: {
				mode: "AUTO";
				bidOverrides?: {
					closeMatch?: number | undefined;
					looseMatch?: number | undefined;
					substitutes?: number | undefined;
					complements?: number | undefined;
				} | undefined;
			} | {
				mode: "MANUAL_KEYWORD";
				keywords: {
					bid: number;
					matchType: "BROAD" | "PHRASE" | "EXACT";
					keyword: string;
				}[];
			} | {
				mode: "MANUAL_PRODUCT";
				products: {
					bid: number;
					asin: string;
				}[];
			};
			negatives?: {
				asins?: string[] | undefined;
				keywords?: {
					matchType: "PHRASE" | "EXACT";
					keyword: string;
				}[] | undefined;
			} | undefined;
		};
		output: {
			campaign: {
				id: string;
				name: string;
				state: "ENABLED" | "PAUSED" | "ARCHIVED";
				deliveryStatus: string;
				startDate: string;
				endDate: string | null;
				bidStrategy: "FIXED" | "DYNAMIC_DOWN_ONLY" | "DYNAMIC_UP_AND_DOWN";
				dailyBudget: number;
				targetingMode: "AUTO" | "MANUAL_KEYWORD" | "MANUAL_PRODUCT";
				placementBidAdjustments?: {
					topOfSearch?: number | undefined;
					restOfSearch?: number | undefined;
					productPages?: number | undefined;
					amazonBusiness?: number | undefined;
				} | undefined;
			};
			adGroup: {
				id: string;
				campaignId: string;
				name: string;
				state: "ENABLED" | "PAUSED" | "ARCHIVED";
				deliveryStatus: string;
				defaultBid: number;
			};
			ads: {
				id: string;
				campaignId: string;
				state: "ENABLED" | "PAUSED" | "ARCHIVED";
				deliveryStatus: string;
				adGroupId: string;
				productTitle: string | null;
				asin: string;
			}[];
			targets: {
				id: string;
				campaignId: string;
				state: "ENABLED" | "PAUSED" | "ARCHIVED";
				deliveryStatus: string;
				adGroupId: string | null;
				negative: boolean;
				type: "AUTO" | "KEYWORD" | "PRODUCT";
				bid?: number | undefined;
				matchType?: string | undefined;
				asin?: string | undefined;
				keyword?: string | undefined;
			}[];
		};
		meta: object;
	}>;
	readonly create_campaign: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			name: string;
			state: "ENABLED" | "PAUSED";
			startDate: string;
			bidStrategy: "FIXED" | "DYNAMIC_DOWN_ONLY" | "DYNAMIC_UP_AND_DOWN";
			dailyBudget: number;
			targetingMode: "AUTO" | "MANUAL_KEYWORD" | "MANUAL_PRODUCT";
			endDate?: string | null | undefined;
			placementBidAdjustments?: {
				topOfSearch?: number | undefined;
				restOfSearch?: number | undefined;
				productPages?: number | undefined;
				amazonBusiness?: number | undefined;
			} | undefined;
		};
		output: {
			id: string;
			name: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			startDate: string;
			endDate: string | null;
			bidStrategy: "FIXED" | "DYNAMIC_DOWN_ONLY" | "DYNAMIC_UP_AND_DOWN";
			dailyBudget: number;
			targetingMode: "AUTO" | "MANUAL_KEYWORD" | "MANUAL_PRODUCT";
			placementBidAdjustments?: {
				topOfSearch?: number | undefined;
				restOfSearch?: number | undefined;
				productPages?: number | undefined;
				amazonBusiness?: number | undefined;
			} | undefined;
		};
		meta: object;
	}>;
	readonly create_ad_group: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			campaignId: string;
			accountId: string;
			name: string;
			state: "ENABLED" | "PAUSED";
			defaultBid: number;
		};
		output: {
			id: string;
			campaignId: string;
			name: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			defaultBid: number;
		};
		meta: object;
	}>;
	readonly create_ad: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			state: "ENABLED" | "PAUSED";
			adGroupId: string;
			asin: string;
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string;
			productTitle: string | null;
			asin: string;
		};
		meta: object;
	}>;
	readonly create_keyword_target: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			state: "ENABLED" | "PAUSED";
			adGroupId: string;
			bid: number;
			matchType: "BROAD" | "PHRASE" | "EXACT";
			keyword: string;
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string | null;
			negative: boolean;
			type: "AUTO" | "KEYWORD" | "PRODUCT";
			bid?: number | undefined;
			matchType?: string | undefined;
			asin?: string | undefined;
			keyword?: string | undefined;
		};
		meta: object;
	}>;
	readonly create_product_target: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			state: "ENABLED" | "PAUSED";
			adGroupId: string;
			bid: number;
			asin: string;
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string | null;
			negative: boolean;
			type: "AUTO" | "KEYWORD" | "PRODUCT";
			bid?: number | undefined;
			matchType?: string | undefined;
			asin?: string | undefined;
			keyword?: string | undefined;
		};
		meta: object;
	}>;
	readonly create_negative_keyword: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			campaignId: string;
			accountId: string;
			state: "ENABLED" | "PAUSED";
			adGroupId: string;
			matchType: "PHRASE" | "EXACT";
			keyword: string;
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string | null;
			negative: boolean;
			type: "AUTO" | "KEYWORD" | "PRODUCT";
			bid?: number | undefined;
			matchType?: string | undefined;
			asin?: string | undefined;
			keyword?: string | undefined;
		};
		meta: object;
	}>;
	readonly create_negative_product_target: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			campaignId: string;
			accountId: string;
			state: "ENABLED" | "PAUSED";
			adGroupId: string;
			asin: string;
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string | null;
			negative: boolean;
			type: "AUTO" | "KEYWORD" | "PRODUCT";
			bid?: number | undefined;
			matchType?: string | undefined;
			asin?: string | undefined;
			keyword?: string | undefined;
		};
		meta: object;
	}>;
	readonly update_campaign: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			campaignId: string;
			accountId: string;
			changes: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | undefined;
				bidStrategy?: "FIXED" | "DYNAMIC_DOWN_ONLY" | "DYNAMIC_UP_AND_DOWN" | undefined;
				dailyBudget?: number | undefined;
				placementBidAdjustments?: {
					topOfSearch?: number | undefined;
					restOfSearch?: number | undefined;
					productPages?: number | undefined;
					amazonBusiness?: number | undefined;
				} | undefined;
			};
		};
		output: {
			id: string;
			name: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			startDate: string;
			endDate: string | null;
			bidStrategy: "FIXED" | "DYNAMIC_DOWN_ONLY" | "DYNAMIC_UP_AND_DOWN";
			dailyBudget: number;
			targetingMode: "AUTO" | "MANUAL_KEYWORD" | "MANUAL_PRODUCT";
			placementBidAdjustments?: {
				topOfSearch?: number | undefined;
				restOfSearch?: number | undefined;
				productPages?: number | undefined;
				amazonBusiness?: number | undefined;
			} | undefined;
		};
		meta: object;
	}>;
	readonly update_ad_group: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			adGroupId: string;
			changes: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | undefined;
				defaultBid?: number | undefined;
			};
		};
		output: {
			id: string;
			campaignId: string;
			name: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			defaultBid: number;
		};
		meta: object;
	}>;
	readonly update_ad: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			adId: string;
			changes: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | undefined;
			};
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string;
			productTitle: string | null;
			asin: string;
		};
		meta: object;
	}>;
	readonly update_target: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			targetId: string;
			changes: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | undefined;
				bid?: number | undefined;
			};
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string | null;
			negative: boolean;
			type: "AUTO" | "KEYWORD" | "PRODUCT";
			bid?: number | undefined;
			matchType?: string | undefined;
			asin?: string | undefined;
			keyword?: string | undefined;
		};
		meta: object;
	}>;
}>>;
export declare const cliAppRouter: import("@trpc/server").TRPCBuiltRouter<{
	ctx: Context;
	meta: object;
	errorShape: {
		data: {
			operationCode: OperationErrorCode;
			details: Record<string, unknown>;
			code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
			httpStatus: number;
			path?: string;
			stack?: string;
		} | {
			operationCode: string;
			details: {
				issues: import("zod").ZodIssue[];
			};
			code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
			httpStatus: number;
			path?: string;
			stack?: string;
		} | {
			code: import("@trpc/server").TRPC_ERROR_CODE_KEY;
			httpStatus: number;
			path?: string;
			stack?: string;
		};
		message: string;
		code: import("@trpc/server").TRPC_ERROR_CODE_NUMBER;
	};
	transformer: false;
}, import("@trpc/server").TRPCDecorateCreateRouterOptions<{
	readonly list_advertiser_accounts: import("@trpc/server").TRPCQueryProcedure<{
		input: {};
		output: {
			accounts: {
				id: string;
				name: string;
				countryCode: string;
				marketplaceId: string;
				currency: string;
				profileId: string | null;
				amazonAdsAccountId: string;
				timezone: string;
			}[];
		};
		meta: object;
	}>;
	readonly search: import("@trpc/server").TRPCQueryProcedure<{
		input: {
			accountId: string;
			resource: "campaign" | "ad_group" | "ad" | "target" | "product" | "change_event";
			orderBy?: {
				field: "campaign.id" | "campaign.name" | "campaign.state" | "campaign.deliveryStatus" | "campaign.dailyBudget" | "campaign.targetingMode" | "campaign.bidStrategy" | "campaign.startDate" | "campaign.endDate" | "adGroup.id" | "adGroup.name" | "adGroup.state" | "adGroup.deliveryStatus" | "adGroup.defaultBid" | "ad.id" | "ad.state" | "ad.deliveryStatus" | "ad.asin" | "ad.productTitle" | "ad.type" | "target.id" | "target.state" | "target.deliveryStatus" | "target.type" | "target.scope" | "target.bid" | "target.negative" | "target.keyword" | "target.asin" | "target.matchType" | "product.asin" | "product.title" | "changeEvent.id" | "changeEvent.resourceType" | "changeEvent.resourceId" | "changeEvent.eventType" | "changeEvent.field" | "changeEvent.previousValue" | "changeEvent.newValue" | "changeEvent.changedAt" | "changeEvent.source" | "metrics.impressions" | "metrics.clicks" | "metrics.spend" | "metrics.orders" | "metrics.sales" | "metrics.acos" | "metrics.cpc" | "metrics.ctr" | "metrics.roas" | "metrics.cvr" | "segments.date" | "segments.hour";
				direction: "asc" | "desc";
			}[] | undefined;
			limit?: number | undefined;
			fields?: ("campaign.id" | "campaign.name" | "campaign.state" | "campaign.deliveryStatus" | "campaign.dailyBudget" | "campaign.targetingMode" | "campaign.bidStrategy" | "campaign.startDate" | "campaign.endDate" | "adGroup.id" | "adGroup.name" | "adGroup.state" | "adGroup.deliveryStatus" | "adGroup.defaultBid" | "ad.id" | "ad.state" | "ad.deliveryStatus" | "ad.asin" | "ad.productTitle" | "ad.type" | "target.id" | "target.state" | "target.deliveryStatus" | "target.type" | "target.scope" | "target.bid" | "target.negative" | "target.keyword" | "target.asin" | "target.matchType" | "product.asin" | "product.title" | "changeEvent.id" | "changeEvent.resourceType" | "changeEvent.resourceId" | "changeEvent.eventType" | "changeEvent.field" | "changeEvent.previousValue" | "changeEvent.newValue" | "changeEvent.changedAt" | "changeEvent.source" | "metrics.impressions" | "metrics.clicks" | "metrics.spend" | "metrics.orders" | "metrics.sales" | "metrics.acos" | "metrics.cpc" | "metrics.ctr" | "metrics.roas" | "metrics.cvr" | "segments.date" | "segments.hour")[] | undefined;
			filters?: {
				field: "campaign.id" | "campaign.name" | "campaign.state" | "campaign.deliveryStatus" | "campaign.dailyBudget" | "campaign.targetingMode" | "campaign.bidStrategy" | "campaign.startDate" | "campaign.endDate" | "adGroup.id" | "adGroup.name" | "adGroup.state" | "adGroup.deliveryStatus" | "adGroup.defaultBid" | "ad.id" | "ad.state" | "ad.deliveryStatus" | "ad.asin" | "ad.productTitle" | "ad.type" | "target.id" | "target.state" | "target.deliveryStatus" | "target.type" | "target.scope" | "target.bid" | "target.negative" | "target.keyword" | "target.asin" | "target.matchType" | "product.asin" | "product.title" | "changeEvent.id" | "changeEvent.resourceType" | "changeEvent.resourceId" | "changeEvent.eventType" | "changeEvent.field" | "changeEvent.previousValue" | "changeEvent.newValue" | "changeEvent.changedAt" | "changeEvent.source" | "metrics.impressions" | "metrics.clicks" | "metrics.spend" | "metrics.orders" | "metrics.sales" | "metrics.acos" | "metrics.cpc" | "metrics.ctr" | "metrics.roas" | "metrics.cvr" | "segments.date" | "segments.hour";
				operator: "eq" | "in" | "contains" | "gt" | "gte" | "lt" | "lte";
				value?: unknown;
			}[] | undefined;
			dateRange?: {
				startDate: string;
				endDate: string;
			} | undefined;
			cursor?: string | undefined;
		};
		output: {
			context: {
				orderBy: {
					field: string;
					direction: "asc" | "desc";
				}[];
				fields: string[];
				account: {
					id: string;
					currency: string;
					timezone: string;
				};
				resource: "campaign" | "ad_group" | "ad" | "target" | "product" | "change_event";
				dateRange?: {
					startDate: string;
					endDate: string;
					source: "DEFAULT" | "EXPLICIT";
				} | undefined;
				coverage?: {
					status: "UNKNOWN" | "COMPLETE" | "INCOMPLETE";
					issues: ({
						date: string;
						status: "PENDING" | "FAILED" | "UNKNOWN";
					} | {
						date: string;
						status: "PARSE_ERRORS";
						errorCount: number;
					})[];
				} | undefined;
			};
			rows: Record<string, unknown>[];
			nextCursor?: string | undefined;
		};
		meta: object;
	}>;
	readonly create_sponsored_products_campaign: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			campaign: {
				name: string;
				state: "ENABLED" | "PAUSED";
				bidStrategy: "FIXED" | "DYNAMIC_DOWN_ONLY" | "DYNAMIC_UP_AND_DOWN";
				dailyBudget: number;
				startDate?: string | undefined;
				endDate?: string | null | undefined;
				placementBidAdjustments?: {
					topOfSearch?: number | undefined;
					restOfSearch?: number | undefined;
					productPages?: number | undefined;
					amazonBusiness?: number | undefined;
				} | undefined;
			};
			accountId: string;
			adGroup: {
				name: string;
				defaultBid: number;
			};
			asins: string[];
			targeting: {
				mode: "AUTO";
				bidOverrides?: {
					closeMatch?: number | undefined;
					looseMatch?: number | undefined;
					substitutes?: number | undefined;
					complements?: number | undefined;
				} | undefined;
			} | {
				mode: "MANUAL_KEYWORD";
				keywords: {
					bid: number;
					matchType: "BROAD" | "PHRASE" | "EXACT";
					keyword: string;
				}[];
			} | {
				mode: "MANUAL_PRODUCT";
				products: {
					bid: number;
					asin: string;
				}[];
			};
			negatives?: {
				asins?: string[] | undefined;
				keywords?: {
					matchType: "PHRASE" | "EXACT";
					keyword: string;
				}[] | undefined;
			} | undefined;
		};
		output: {
			campaign: {
				id: string;
				name: string;
				state: "ENABLED" | "PAUSED" | "ARCHIVED";
				deliveryStatus: string;
				startDate: string;
				endDate: string | null;
				bidStrategy: "FIXED" | "DYNAMIC_DOWN_ONLY" | "DYNAMIC_UP_AND_DOWN";
				dailyBudget: number;
				targetingMode: "AUTO" | "MANUAL_KEYWORD" | "MANUAL_PRODUCT";
				placementBidAdjustments?: {
					topOfSearch?: number | undefined;
					restOfSearch?: number | undefined;
					productPages?: number | undefined;
					amazonBusiness?: number | undefined;
				} | undefined;
			};
			adGroup: {
				id: string;
				campaignId: string;
				name: string;
				state: "ENABLED" | "PAUSED" | "ARCHIVED";
				deliveryStatus: string;
				defaultBid: number;
			};
			ads: {
				id: string;
				campaignId: string;
				state: "ENABLED" | "PAUSED" | "ARCHIVED";
				deliveryStatus: string;
				adGroupId: string;
				productTitle: string | null;
				asin: string;
			}[];
			targets: {
				id: string;
				campaignId: string;
				state: "ENABLED" | "PAUSED" | "ARCHIVED";
				deliveryStatus: string;
				adGroupId: string | null;
				negative: boolean;
				type: "AUTO" | "KEYWORD" | "PRODUCT";
				bid?: number | undefined;
				matchType?: string | undefined;
				asin?: string | undefined;
				keyword?: string | undefined;
			}[];
		};
		meta: object;
	}>;
	readonly create_campaign: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			name: string;
			state: "ENABLED" | "PAUSED";
			startDate: string;
			bidStrategy: "FIXED" | "DYNAMIC_DOWN_ONLY" | "DYNAMIC_UP_AND_DOWN";
			dailyBudget: number;
			targetingMode: "AUTO" | "MANUAL_KEYWORD" | "MANUAL_PRODUCT";
			endDate?: string | null | undefined;
			placementBidAdjustments?: {
				topOfSearch?: number | undefined;
				restOfSearch?: number | undefined;
				productPages?: number | undefined;
				amazonBusiness?: number | undefined;
			} | undefined;
		};
		output: {
			id: string;
			name: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			startDate: string;
			endDate: string | null;
			bidStrategy: "FIXED" | "DYNAMIC_DOWN_ONLY" | "DYNAMIC_UP_AND_DOWN";
			dailyBudget: number;
			targetingMode: "AUTO" | "MANUAL_KEYWORD" | "MANUAL_PRODUCT";
			placementBidAdjustments?: {
				topOfSearch?: number | undefined;
				restOfSearch?: number | undefined;
				productPages?: number | undefined;
				amazonBusiness?: number | undefined;
			} | undefined;
		};
		meta: object;
	}>;
	readonly create_ad_group: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			campaignId: string;
			accountId: string;
			name: string;
			state: "ENABLED" | "PAUSED";
			defaultBid: number;
		};
		output: {
			id: string;
			campaignId: string;
			name: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			defaultBid: number;
		};
		meta: object;
	}>;
	readonly create_ad: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			state: "ENABLED" | "PAUSED";
			adGroupId: string;
			asin: string;
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string;
			productTitle: string | null;
			asin: string;
		};
		meta: object;
	}>;
	readonly create_keyword_target: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			state: "ENABLED" | "PAUSED";
			adGroupId: string;
			bid: number;
			matchType: "BROAD" | "PHRASE" | "EXACT";
			keyword: string;
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string | null;
			negative: boolean;
			type: "AUTO" | "KEYWORD" | "PRODUCT";
			bid?: number | undefined;
			matchType?: string | undefined;
			asin?: string | undefined;
			keyword?: string | undefined;
		};
		meta: object;
	}>;
	readonly create_product_target: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			state: "ENABLED" | "PAUSED";
			adGroupId: string;
			bid: number;
			asin: string;
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string | null;
			negative: boolean;
			type: "AUTO" | "KEYWORD" | "PRODUCT";
			bid?: number | undefined;
			matchType?: string | undefined;
			asin?: string | undefined;
			keyword?: string | undefined;
		};
		meta: object;
	}>;
	readonly create_negative_keyword: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			campaignId: string;
			accountId: string;
			state: "ENABLED" | "PAUSED";
			adGroupId: string;
			matchType: "PHRASE" | "EXACT";
			keyword: string;
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string | null;
			negative: boolean;
			type: "AUTO" | "KEYWORD" | "PRODUCT";
			bid?: number | undefined;
			matchType?: string | undefined;
			asin?: string | undefined;
			keyword?: string | undefined;
		};
		meta: object;
	}>;
	readonly create_negative_product_target: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			campaignId: string;
			accountId: string;
			state: "ENABLED" | "PAUSED";
			adGroupId: string;
			asin: string;
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string | null;
			negative: boolean;
			type: "AUTO" | "KEYWORD" | "PRODUCT";
			bid?: number | undefined;
			matchType?: string | undefined;
			asin?: string | undefined;
			keyword?: string | undefined;
		};
		meta: object;
	}>;
	readonly update_campaign: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			campaignId: string;
			accountId: string;
			changes: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | undefined;
				bidStrategy?: "FIXED" | "DYNAMIC_DOWN_ONLY" | "DYNAMIC_UP_AND_DOWN" | undefined;
				dailyBudget?: number | undefined;
				placementBidAdjustments?: {
					topOfSearch?: number | undefined;
					restOfSearch?: number | undefined;
					productPages?: number | undefined;
					amazonBusiness?: number | undefined;
				} | undefined;
			};
		};
		output: {
			id: string;
			name: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			startDate: string;
			endDate: string | null;
			bidStrategy: "FIXED" | "DYNAMIC_DOWN_ONLY" | "DYNAMIC_UP_AND_DOWN";
			dailyBudget: number;
			targetingMode: "AUTO" | "MANUAL_KEYWORD" | "MANUAL_PRODUCT";
			placementBidAdjustments?: {
				topOfSearch?: number | undefined;
				restOfSearch?: number | undefined;
				productPages?: number | undefined;
				amazonBusiness?: number | undefined;
			} | undefined;
		};
		meta: object;
	}>;
	readonly update_ad_group: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			adGroupId: string;
			changes: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | undefined;
				defaultBid?: number | undefined;
			};
		};
		output: {
			id: string;
			campaignId: string;
			name: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			defaultBid: number;
		};
		meta: object;
	}>;
	readonly update_ad: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			adId: string;
			changes: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | undefined;
			};
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string;
			productTitle: string | null;
			asin: string;
		};
		meta: object;
	}>;
	readonly update_target: import("@trpc/server").TRPCMutationProcedure<{
		input: {
			accountId: string;
			targetId: string;
			changes: {
				state?: "ENABLED" | "PAUSED" | "ARCHIVED" | undefined;
				bid?: number | undefined;
			};
		};
		output: {
			id: string;
			campaignId: string;
			state: "ENABLED" | "PAUSED" | "ARCHIVED";
			deliveryStatus: string;
			adGroupId: string | null;
			negative: boolean;
			type: "AUTO" | "KEYWORD" | "PRODUCT";
			bid?: number | undefined;
			matchType?: string | undefined;
			asin?: string | undefined;
			keyword?: string | undefined;
		};
		meta: object;
	}>;
}>>;
export type PublicAppRouter = typeof publicAppRouter;
export type CliAppRouter = PublicAppRouter;

export {};
