nmHoistingLimits: none
nodeLinker: node-modules
supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl

injectEnvironmentFiles:
  - .env

npmScopes:
  merchbaseco:
    npmRegistryServer: "https://npm.pkg.github.com/"
    npmAuthToken: "${MERCHBASE_NPM_TOKEN}"

